import type { Project, Task } from "./types";

export const projects: Project[] = [
  { id: "personal", name: "Personal", type: "personal", color: "#6f7cff" },
  { id: "flywheel", name: "Flywheel", type: "work", color: "#111111" },
  { id: "consulting", name: "Consulting", type: "work", color: "#2e8b57" },
  { id: "sidecar", name: "Side Project", type: "side-project", color: "#d97706" },
];

export const seededTasks: Task[] = [
  {
    id: "task-1",
    title: "Finalize Flywheel workshop agenda",
    description: "Lock the session structure and share the final narrative for review.",
    projectId: "flywheel",
    status: "next",
    priority: "critical",
    dueDate: "2026-03-21",
    scheduledDate: "2026-03-21",
    startDate: "2026-03-21",
    owner: "Rahul",
    dependencyLabel: null,
    effort: "deep",
    tags: ["planning", "strategy"],
  },
  {
    id: "task-2",
    title: "Follow up on consulting numbers",
    description: "Need latest revenue breakdown before drafting recommendations.",
    projectId: "consulting",
    status: "waiting",
    priority: "high",
    dueDate: "2026-03-22",
    scheduledDate: null,
    startDate: "2026-03-21",
    owner: "Rahul",
    dependencyLabel: "Waiting on finance team",
    effort: "quick",
    tags: ["follow-up"],
  },
  {
    id: "task-3",
    title: "Book annual health checkup",
    description: "Pick a date and lock the appointment before slots disappear.",
    projectId: "personal",
    status: "inbox",
    priority: "medium",
    dueDate: "2026-03-25",
    scheduledDate: null,
    startDate: null,
    owner: "Rahul",
    dependencyLabel: null,
    effort: "quick",
    tags: ["health", "life-admin"],
  },
  {
    id: "task-4",
    title: "Review side project landing page copy",
    description: "Tighten the headline, CTA, and benefits section.",
    projectId: "sidecar",
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-03-24",
    scheduledDate: "2026-03-23",
    startDate: "2026-03-21",
    owner: "Rahul",
    dependencyLabel: null,
    effort: "medium",
    tags: ["marketing", "copy"],
  },
  {
    id: "task-5",
    title: "Send consultant invoice",
    description: "Quick win that has been sitting too long.",
    projectId: "consulting",
    status: "next",
    priority: "high",
    dueDate: "2026-03-20",
    scheduledDate: "2026-03-21",
    startDate: "2026-03-20",
    owner: "Rahul",
    dependencyLabel: null,
    effort: "quick",
    tags: ["finance"],
  },
  {
    id: "task-6",
    title: "Delegate logo refinement",
    description: "Hand off the polish round and confirm delivery timing.",
    projectId: "sidecar",
    status: "delegated",
    priority: "low",
    dueDate: "2026-03-26",
    scheduledDate: null,
    startDate: "2026-03-21",
    owner: "Designer",
    dependencyLabel: "Delegated to freelance designer",
    effort: "quick",
    tags: ["design"],
  },
  {
    id: "task-7",
    title: "Prepare Sunday family travel shortlist",
    description: "Compare two nearby options and estimate budget.",
    projectId: "personal",
    status: "next",
    priority: "medium",
    dueDate: "2026-03-23",
    scheduledDate: "2026-03-22",
    startDate: "2026-03-21",
    owner: "Rahul",
    dependencyLabel: null,
    effort: "medium",
    tags: ["family", "planning"],
  },
  {
    id: "task-8",
    title: "Confirm venue AV constraints",
    description: "Blocked until the organizer shares the latest venue deck.",
    projectId: "flywheel",
    status: "blocked",
    priority: "high",
    dueDate: "2026-03-23",
    scheduledDate: null,
    startDate: "2026-03-21",
    owner: "Rahul",
    dependencyLabel: "Blocked by organizer response",
    effort: "quick",
    tags: ["ops"],
  },
];
